apiVersion: apps/v1
kind: Deployment
metadata:
  name: wardrobe-frontend
  namespace: wardrobe-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wardrobe-frontend
  template:
    metadata:
      labels:
        app: wardrobe-frontend
    spec:
      containers:
      - name: frontend
        image: wardrobe-ai/frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: wardrobe-frontend
  namespace: wardrobe-ai
spec:
  selector:
    app: wardrobe-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
