apiVersion: apps/v1
kind: Deployment
metadata:
  name: wardrobe-ai-service
  namespace: wardrobe-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wardrobe-ai-service
  template:
    metadata:
      labels:
        app: wardrobe-ai-service
    spec:
      containers:
      - name: ai-service
        image: wardrobe-ai/ai-service:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: wardrobe-config
        - secretRef:
            name: wardrobe-secrets
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: wardrobe-ai-service
  namespace: wardrobe-ai
spec:
  selector:
    app: wardrobe-ai-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
